spring.application.name=granoAndClick
spring.datasource.url=jdbc:mysql://localhost:33061/granoAndClick
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
