spring.application.name=granoAndClick

spring.datasource.url=jdbc:mysql://127.0.0.1:3307/granoAndClick
spring.datasource.username=emmanuel
spring.datasource.password=Pa$$w0rd

spring.jpa.hibernate.ddl-auto=update
